# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(265, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LoginAndPass = QtWidgets.QFrame(self.centralwidget)
        self.LoginAndPass.setMaximumSize(QtCore.QSize(245, 72))
        self.LoginAndPass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoginAndPass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginAndPass.setObjectName("LoginAndPass")
        self.gridLayout = QtWidgets.QGridLayout(self.LoginAndPass)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_login = QtWidgets.QLabel(self.LoginAndPass)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_login.setFont(font)
        self.lbl_login.setObjectName("lbl_login")
        self.gridLayout.addWidget(self.lbl_login, 0, 0, 1, 1)
        self.edit_login = QtWidgets.QLineEdit(self.LoginAndPass)
        self.edit_login.setObjectName("edit_login")
        self.gridLayout.addWidget(self.edit_login, 0, 1, 1, 1)
        self.lbl_password = QtWidgets.QLabel(self.LoginAndPass)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_password.setFont(font)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout.addWidget(self.lbl_password, 1, 0, 1, 1)
        self.edit_password = QtWidgets.QLineEdit(self.LoginAndPass)
        self.edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_password.setObjectName("edit_password")
        self.gridLayout.addWidget(self.edit_password, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.LoginAndPass)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(245, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_name2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_name2.setFont(font)
        self.lbl_name2.setObjectName("lbl_name2")
        self.gridLayout_2.addWidget(self.lbl_name2, 0, 0, 1, 1)
        self.edit_name2 = QtWidgets.QLineEdit(self.frame_2)
        self.edit_name2.setObjectName("edit_name2")
        self.gridLayout_2.addWidget(self.edit_name2, 0, 1, 1, 1)
        self.lbl_name1 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_name1.setFont(font)
        self.lbl_name1.setObjectName("lbl_name1")
        self.gridLayout_2.addWidget(self.lbl_name1, 1, 0, 1, 1)
        self.edit_name1 = QtWidgets.QLineEdit(self.frame_2)
        self.edit_name1.setObjectName("edit_name1")
        self.gridLayout_2.addWidget(self.edit_name1, 1, 1, 1, 1)
        self.lbl_name3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_name3.setFont(font)
        self.lbl_name3.setObjectName("lbl_name3")
        self.gridLayout_2.addWidget(self.lbl_name3, 2, 0, 1, 1)
        self.edit_name3 = QtWidgets.QLineEdit(self.frame_2)
        self.edit_name3.setObjectName("edit_name3")
        self.gridLayout_2.addWidget(self.edit_name3, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout.addWidget(self.btn_register)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_login.setText(_translate("MainWindow", "Login"))
        self.lbl_password.setText(_translate("MainWindow", "Password"))
        self.lbl_name2.setText(_translate("MainWindow", "First name"))
        self.lbl_name1.setText(_translate("MainWindow", "Last name"))
        self.lbl_name3.setText(_translate("MainWindow", "Patronymic"))
        self.btn_register.setText(_translate("MainWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
