# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddNewProduct.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_New_Product(object):
    def setupUi(self, Add_New_Product):
        Add_New_Product.setObjectName("Add_New_Product")
        Add_New_Product.resize(285, 247)
        self.centralwidget = QtWidgets.QWidget(Add_New_Product)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.lab_name = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_name.setFont(font)
        self.lab_name.setObjectName("lab_name")
        self.gridLayout.addWidget(self.lab_name, 0, 0, 1, 1)
        self.edit_name = QtWidgets.QLineEdit(self.frame)
        self.edit_name.setEnabled(True)
        self.edit_name.setObjectName("edit_name")
        self.gridLayout.addWidget(self.edit_name, 0, 1, 1, 1)
        self.lab_price = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_price.setFont(font)
        self.lab_price.setObjectName("lab_price")
        self.gridLayout.addWidget(self.lab_price, 1, 0, 1, 1)
        self.spinBox_price = QtWidgets.QSpinBox(self.frame)
        self.spinBox_price.setObjectName("spinBox_price")
        self.gridLayout.addWidget(self.spinBox_price, 1, 1, 1, 1)
        self.lab_category = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_category.setFont(font)
        self.lab_category.setObjectName("lab_category")
        self.gridLayout.addWidget(self.lab_category, 2, 0, 1, 1)
        self.comboBox_category = QtWidgets.QComboBox(self.frame)
        self.comboBox_category.setObjectName("comboBox_category")
        self.gridLayout.addWidget(self.comboBox_category, 2, 1, 1, 1)
        self.lab_manufacturer = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_manufacturer.setFont(font)
        self.lab_manufacturer.setObjectName("lab_manufacturer")
        self.gridLayout.addWidget(self.lab_manufacturer, 3, 0, 1, 1)
        self.comboBox_manafacturer = QtWidgets.QComboBox(self.frame)
        self.comboBox_manafacturer.setObjectName("comboBox_manafacturer")
        self.gridLayout.addWidget(self.comboBox_manafacturer, 3, 1, 1, 1)
        self.lab_amount = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_amount.setFont(font)
        self.lab_amount.setObjectName("lab_amount")
        self.gridLayout.addWidget(self.lab_amount, 4, 0, 1, 1)
        self.spinBox_amount = QtWidgets.QSpinBox(self.frame)
        self.spinBox_amount.setObjectName("spinBox_amount")
        self.gridLayout.addWidget(self.spinBox_amount, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        Add_New_Product.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Add_New_Product)
        self.statusbar.setObjectName("statusbar")
        Add_New_Product.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Add_New_Product)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 285, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        Add_New_Product.setMenuBar(self.menuBar)
        self.actionAdd_catecory = QtWidgets.QAction(Add_New_Product)
        self.actionAdd_catecory.setObjectName("actionAdd_catecory")
        self.actionAdd_manufacturer = QtWidgets.QAction(Add_New_Product)
        self.actionAdd_manufacturer.setObjectName("actionAdd_manufacturer")
        self.menuMenu.addAction(self.actionAdd_catecory)
        self.menuMenu.addAction(self.actionAdd_manufacturer)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(Add_New_Product)
        QtCore.QMetaObject.connectSlotsByName(Add_New_Product)

    def retranslateUi(self, Add_New_Product):
        _translate = QtCore.QCoreApplication.translate
        Add_New_Product.setWindowTitle(_translate("Add_New_Product", "MainWindow"))
        self.lab_name.setText(_translate("Add_New_Product", "Name"))
        self.lab_price.setText(_translate("Add_New_Product", "Price"))
        self.lab_category.setText(_translate("Add_New_Product", "Category"))
        self.lab_manufacturer.setText(_translate("Add_New_Product", "Manufacturer"))
        self.lab_amount.setText(_translate("Add_New_Product", "Amount"))
        self.btn_add.setText(_translate("Add_New_Product", "Add"))
        self.menuMenu.setTitle(_translate("Add_New_Product", "Menu"))
        self.actionAdd_catecory.setText(_translate("Add_New_Product", "Add catecory"))
        self.actionAdd_manufacturer.setText(_translate("Add_New_Product", "Add manufacturer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_New_Product = QtWidgets.QMainWindow()
    ui = Ui_Add_New_Product()
    ui.setupUi(Add_New_Product)
    Add_New_Product.show()
    sys.exit(app.exec_())
